# Generated by Django 4.2.2 on 2023-07-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('numero_animal', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('raca', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_doenca', models.CharField(max_length=255)),
                ('data_diagnostico', models.DateField()),
                ('tratamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuidado', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parasita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_parasita', models.CharField(max_length=255)),
                ('data_tratamento', models.DateField()),
                ('data_prixima_aplicaçao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('numero', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(max_length=255)),
                ('data_administracao', models.DateField()),
                ('data_vencimento', models.DateField()),
            ],
        ),
    ]
